name: CI
on:
  push:
    branches: releases/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - id: get-version
        uses: actions/github-script@0.9.0
        with:
          script: |
            const branch = '${{github.ref}}';
            const id = branch.split('/').reverse()[0];
            core.setOutput('id', id);
      - run: dotnet pack -p:PackageVersion=${{steps.get-version.outputs.id}}
          
